#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWF-Header
version:      0.03
version_from: lib/SWF/Header.pm
installdirs:  site
requires:
    SWF::BinStream:                0.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
